# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-docstring-first
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: forbid-submodules
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: ruff
        name: Ruff Linter
        entry: uv
        language: system
        types: [python]
        args: ["run", "ruff", "check", "--fix"]
        always_run: true

    -   id: mypy
        name: MyPy Type-Checker
        entry: uv
        language: system
        types: [python]
        args: ["run", "mypy"]
        always_run: true

    -   id: pytest
        name: PyTest
        entry: uv
        language: system
        types: [python]
        args: ["run", "pytest"]
        always_run: true
        pass_filenames: false
