name: Documentation

# build the documentation whenever there are new commits on main and for tags
on:
  push:
    tags:
       - '*'
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install chordnet dependencies
        run: uv sync --frozen --all-extras --dev

      - name: Build library docs (public API)
        run: |
          # pdoc default generates only public (non-private) members
          uv run pdoc --docformat google -o docs/library chordnet

      - name: Build developer docs (include private/internal)
        run: |
          # include private/internal members for developer docs
          uv run pdoc --docformat google --private -o docs/dev chordnet

      - name: Write simple landing index
        run: |
          mkdir -p docs
          cat > docs/index.html <<'HTML'
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width,initial-scale=1" />
              <title>Chordnet documentation</title>
              <style>
                body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial; max-width: 900px; margin: 3rem auto; padding: 0 1rem; }
                h1 { margin-bottom: 0.25rem; }
                p { color: #444; }
                .links { margin-top: 1.25rem; }
                .links a { display:inline-block; margin-right:1rem; padding: 0.5rem 0.75rem; background:#f3f4f6; color:#111; text-decoration:none; border-radius:6px; }
              </style>
            </head>
            <body>
              <h1>Chordnet documentation</h1>
              <p>Choose the set of docs you want to view:</p>
              <div class="links">
                <a href="./library/">Library (public)</a>
                <a href="./dev/">Developer (internal)</a>
              </div>
            </body>
          </html>
          HTML

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  # Deploy the artifact to GitHub Pages.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
