name: Documentation

# build the documentation whenever there are new commits on main and for tags
on:
  push:
    tags:
       - '*'
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install chordnet dependencies
        run: uv sync --frozen --all-extras --dev

      - name: Build library docs
        run: uv run pdoc --no-show-source --docformat google -o docs/ chordnet

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  # Deploy the artifact to GitHub Pages.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
