# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Matrix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

        
    uses: ./.github/workflows/reusable/pipeline.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      run-lint: true
      run-typecheck: true
      run-test: true
      run-build: false
