# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: 
  workflow_dispatch:
#  release:
#    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.19"
          enable-cache: true

      - name: Install chordnet
        run: uv sync --locked --all-extras --dev
        
      - name: Run linter
        run: uv run ruff check --output-format=github .
        
      - name: Run tests
        run: uv run pytest
      
      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish --index testpypi
